refactor KubernetesJob and KubernetesJobRun to use existing task functions.
PrefectHQ/prefect-kubernetes pull request #43
Opened 2023-03-24 17:42 UTC by tardunge

- Use existing tasks to create, read, delete or fetch job status.
    - Use existing pods tasks to list pods and read pod logs.
    - Added read_namespaced_job_status task.

Closes

### Example

### Screenshots

### Checklist

- [ ] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-kubernetes/issues/new/choose) first.
- [ ] Includes tests or only affects documentation.
- [ ] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [ ] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-kubernetes/blob/main/CHANGELOG.md)

2023-03-25 19:20 UTC, tardunge commented
This initialises and closes several kubernetes clients. However, the `run_namespaced_job` flow doesn't encounter `TCP_CONN_TIMEOUT` errors.

2023-03-27 14:59 UTC, desertaxle requested changes
Thanks for your contribution @tardunge!

Could you please summarize your changes in `CHANGELOG.md`?

2023-03-27 14:59 UTC, desertaxle commented on prefect_kubernetes/jobs.py
> +        job_name: The name of a job to fetch the status.
```suggestion
        job_name: The name of a job to fetch status for.
```

2023-03-27 15:35 UTC, tardunge commented
> lexander Streed <desertaxle@users.noreply.github.com>
> 
>     
> 
> 
> 
>       
>           
> 
>   
> 
>   [
>         <img alt="@tardunge" width="20" height="20" src="https://avatars.githubusercontent.com/u/1139145?s=40&amp;v=4">
> ](/tardunge)

Tq. Updated the CHANGELOG.md file.

2023-03-27 16:03 UTC, tardunge commented on CHANGELOG.md
> +- Refactor KubernetesJob and KubernetesJobRun to use existing task functions.
done.

2023-03-27 16:06 UTC, tardunge commented on CHANGELOG.md
> +- Refactor KubernetesJob and KubernetesJobRun to use existing task functions.
done.

2023-03-27 16:08 UTC, desertaxle requested changes

2023-03-27 16:08 UTC, desertaxle commented on CHANGELOG.md
> +- Refactor KubernetesJob and KubernetesJobRun to use existing task functions.
```suggestion
- Refactor KubernetesJob and KubernetesJobRun to use existing task functions - [#43](https://github.com/PrefectHQ/prefect-kubernetes/pull/43)
```

2023-03-27 16:41 UTC, desertaxle approved these changes
LGTM!

2023-03-27 16:41 UTC, merged