support tasks for managing kubernetes custom resources
PrefectHQ/prefect-kubernetes pull request #45
Opened 2023-03-25 18:54 UTC by tardunge

Closes #44 

### Example

### Screenshots
Mkdocs:
<img width="1366" alt="Screenshot 2023-03-26 at 12 08 01 AM" src="https://user-images.githubusercontent.com/1139145/227735819-edc46b4f-39f5-418a-9623-8866d4a11e2e.png">

Service Integration tests:
<img width="1438" alt="Screenshot 2023-03-26 at 12 20 12 AM" src="https://user-images.githubusercontent.com/1139145/227735909-b58fa1db-b5f5-4787-bac0-62cd5a21da0a.png">

### Checklist

- [ ] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-kubernetes/issues/new/choose) first.
- [ ] Includes tests or only affects documentation.
- [ ] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [ ] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-kubernetes/blob/main/CHANGELOG.md)

2023-03-25 18:56 UTC, tardunge commented
Contains only crud operations for namespaced scope.
Should we add cluster scoped operations as well?

2023-03-27 14:52 UTC, desertaxle requested changes
Thanks for your contribution @tardunge! 

Overall this looks great! In addition to the comments on typings and docstrings, could you please add an entry to `CHANGELOG.md`?

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +            Kubernetes API (e.g. `{"pretty": "...", "dry_run": "..."}`).
```suggestion
    Args:
        kubernetes_credentials: KubernetesCredentials block
            holding authentication needed to generate the required API client.
        group: The custom resource object's group
        version: The custom resource object's version
        plural: The custom resource object's plural
        name: The name of a custom object to replace.
        body: A Dict containing the custom resource object's specification.
        namespace: The custom resource's Kubernetes namespace.
        **kube_kwargs: Optional extra keyword arguments to pass to the
            Kubernetes API (e.g. `{"pretty": "...", "dry_run": "..."}`).
```

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +        namespace: The Kubernetes namespace to read this custom resource is in.
```suggestion
        namespace: The Kubernetes namespace the custom resource is in.
```

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +    namespace: Optional[str] = "default",
```suggestion
    namespace: str = "default",
```

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +    namespace: Optional[str] = "default",
```suggestion
    namespace: str = "default",
```

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +        namespace: The Kubernetes namespace to create this custom object in.
```suggestion
        namespace: The Kubernetes namespace the custom object is in.
```

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +    namespace: Optional[str] = "default",
```suggestion
    namespace: str = "default",
```

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +        namespace: The Kubernetes namespace to create this custom object in.
```suggestion
        namespace: The Kubernetes namespace to create the custom object in.
```

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +    namespace: Optional[str] = "default",
```suggestion
    namespace: str = "default",
```

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +    namespace: Optional[str] = "default",
```suggestion
    namespace: str = "default",
```

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +    namespace: Optional[str] = "default",
```suggestion
    namespace: str = "default",
```

2023-03-27 14:52 UTC, desertaxle commented on prefect_kubernetes/custom_objects.py
> +    namespace: Optional[str] = "default",
```suggestion
    namespace: str = "default",
```

2023-03-27 15:44 UTC, tardunge commented
> Thanks for your contribution @tardunge!
> 
> Overall this looks great! In addition to the comments on typings and docstrings, could you please add an entry to `CHANGELOG.md`?

Done.

2023-03-27 16:07 UTC, tardunge commented on CHANGELOG.md
> +- Custom objects crud tasks for kubernetes custom resource definitions. - [#45](https://github.com/PrefectHQ/prefect-kubernetes/pull/45)
done.

2023-03-27 16:25 UTC, desertaxle approved these changes
LGTM!

2023-03-27 16:25 UTC, merged